ALTER TABLE IF EXISTS users
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (INCREMENT 1),
    ADD PRIMARY KEY (id);

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

ALTER TABLE IF EXISTS movies
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (INCREMENT 1),
    ADD PRIMARY KEY (id);

SELECT setval('movies_id_seq', (SELECT MAX(id) FROM movies));